# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e465436851bc91835a027d7e0cae139"
name = "kastelar connect"
application_url = "https://kastelar-remix-jqw0q558o-jayeshs-projects-db87986c.vercel.app"
embedded = true
handle = "kastelar-connect"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_products,write_products,read_metaobjects,write_metaobjects"


[auth]
redirect_urls = [
  "https://kastelar-remix-jqw0q558o-jayeshs-projects-db87986c.vercel.app/auth/callback",
  "https://kastelar-remix-jqw0q558o-jayeshs-projects-db87986c.vercel.app/auth/shopify/callback",
  "https://kastelar-remix-jqw0q558o-jayeshs-projects-db87986c.vercel.app/api/auth/callback"
]

[pos]
embedded = false